[package]
name = "bevy_fuse"
version = "0.1.0"
edition = "2024"

[dependencies]
avian2d = "0.4.1"
bevy = "0.17.3"
clap = { version = "4.5.53", features = ["cargo"] }
fuser = "0.16.0"
libc = "0.2.178"
rand = "0.9.2"
